// <auto-generated />
using System;
using CapsuleCorp.Monitor.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CapsuleCorp.Monitor.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CapsuleCorp.Monitor.API.Models.TelemetryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ChillerWaterFlowLpm")
                        .HasColumnType("double precision");

                    b.Property<string>("EquipmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("GantryVibrationG")
                        .HasColumnType("double precision");

                    b.Property<double>("GradientCurrentAmperes")
                        .HasColumnType("double precision");

                    b.Property<double>("HostCpuTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<double>("HostStorageFreePercentage")
                        .HasColumnType("double precision");

                    b.Property<double>("MagnetCompressorLinePressurePsi")
                        .HasColumnType("double precision");

                    b.Property<string>("MagnetCompressorStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MagnetHeliumLevelPercentage")
                        .HasColumnType("double precision");

                    b.Property<double>("MagnetTemperatureKelvin")
                        .HasColumnType("double precision");

                    b.Property<double>("MagnetVesselHeliumPressurePsi")
                        .HasColumnType("double precision");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PowerSupplyVoltage")
                        .HasColumnType("double precision");

                    b.Property<double>("RoomHumidityPercentage")
                        .HasColumnType("double precision");

                    b.Property<double>("RoomTemperatureCelsius")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId", "Timestamp");

                    b.ToTable("TelemetryHistories", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
